version: "3.8"

services:
  mongo1:
    image: mongo:7.0.7
    restart: always
    container_name: mongo1
    command: --replSet ${REPLICA_SET} --bind_ip_all --port ${MONGO_PORT}
    volumes:
      - crud_service:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    healthcheck:
      test: test $$(mongosh --port ${MONGO_PORT} --quiet --eval "rs.initiate({_id:\"${REPLICA_SET}\",members:[{_id:0,host:\"localhost:${MONGO_PORT}\"}]}).ok || rs.status().ok") -eq 1
      interval: 20s
      timeout: 10s
      retries: 6
  
volumes:
  crud_service:
